FROM bluebrain/brayns:latest
RUN mkdir -p /build /sbo/data/project
WORKDIR /build
RUN apt update && apt install -y s3fs curl unzip telnet && apt clean
RUN curl -k "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install && rm -rf /build

ADD ./mount_s3.sh /app
WORKDIR /app
ENTRYPOINT ["/bin/bash"]
